set -x

export VLLM_USE_V1=0
# gsm8k_train_path=$HOME/data/gsm8k/train.parquet
# gsm8k_test_path=$HOME/data/gsm8k/test.parquet
math_train_path=/angel/fwk/code/verl/data/math/train.parquet
math_test_path=/angel/fwk/code/verl/data/math/test.parquet

# train_files="['$gsm8k_train_path', '$math_train_path']"
train_files="['$math_train_path']"
test_files="['$math_test_path']"
# data.filter_overlong_prompts=True \
python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=reinforce_plus_plus_baseline \
    data.train_files="$train_files" \
    data.val_files="$test_files" \
    data.train_batch_size=1 \
    data.max_prompt_length=1536 \
    data.max_response_length=512 \
    data.truncation='error' \
    actor_rollout_ref.model.path=/angel/fwk/models/deepseek-ai/DeepSeek-R1-Distill-Llama-8B \
    actor_rollout_ref.actor.optim.lr=3e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=1 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=mse \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.n=16 \
    actor_rollout_ref.rollout.temperature=0.6 \
    actor_rollout_ref.rollout.top_p=0.95 \
    actor_rollout_ref.rollout.enforce_eager=True \
    actor_rollout_ref.rollout.free_cache_engine=False \
    actor_rollout_ref.rollout.max_num_batched_tokens=2080 \
    actor_rollout_ref.rollout.max_model_len=2080 \
    actor_rollout_ref.rollout.enable_chunked_prefill=False \
    actor_rollout_ref.rollout.sae.enable=True \
    actor_rollout_ref.rollout.sae.strengths=\"1.0,1.0\" \
    actor_rollout_ref.rollout.sae.release="andreuka18/deepseek-r1-distill-llama-8b-lmsys-openthoughts" \
    actor_rollout_ref.rollout.sae.id="blocks.19.hook_resid_post" \
    actor_rollout_ref.rollout.sae.feature_idxs=\"1160,1230\" \
    actor_rollout_ref.rollout.sae.max_activations=\"5.0,5.0\" \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.use_kl_in_reward=True \
    trainer.critic_warmup=0 \
    trainer.logger='["console"]' \
    trainer.project_name='verl_grpo_example_gsm8k' \
    trainer.experiment_name='llama32_3b_function_rm' \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=-1 \
    trainer.test_freq=5 \
    trainer.total_epochs=15 $@
